import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { CustomConnectionButton } from "../components/CustomConnectionButton";
import HomeView from "../views/HomeView";

const Home: NextPage = () => {
  return (
    <div style={{background:"green"}}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <HomeView />
    </div>
  );
};

export default Home;
